SELECT S.SNAME, B.SNAME AS boss_name
FROM SELLERS S
LEFT JOIN SELLERS B
ON S.BOSS_ID = B.SELL_ID;

SELECT s.CNAME, o.AMT
FROM CUSTOMERS s
INNER JOIN ORDERS o
ON s.cust_id = o.cust_id
WHERE o.AMT > 1000;

SELECT C.CNAME, S.SNAME
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUST_ID = O.CUST_ID
INNER JOIN SELLERS S
ON O.SELL_ID = S.SELL_ID
WHERE C.CITY <> S.CITY;

SELECT C.CNAME, O.ORDER_ID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUST_ID = O.CUST_ID
UNION
SELECT C.CNAME, O.ORDER_ID
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUST_ID = O.CUST_ID;

SELECT s.SNAME, (s.comm - b.comm) AS difference
FROM SELLERS s
LEFT JOIN SELLERS b
ON s.BOSS_ID = b.SELL_ID;

SELECT C.CNAME, S.SNAME
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUST_ID = O.CUST_ID
JOIN SELLERS S
ON O.SELL_ID = S.SELL_ID
WHERE C.CITY = S.CITY;
